### ISSUE TITLE
E2001: failed to update vendor image (missing preload partition?) - Lineageos 16.0

### ISSUE THREAD

**Issue by mtarunsai1999** [karthick111/android_kernel_lenovo_msm8937#5]
hi, i don't know if this is the correct place to ask this. I'm trying to flash lineageos 16.0 on my k6 power. I'm currently using pixelexperience rom for this device. I get the above error. I checked the updater-script in the zip and found these lines(18,19) 

`block_image_update("/dev/block/bootdevice/by-name/preload", package_extract_file("vendor.transfer.list"), "vendor.new.dat.br", "vendor.patch.dat") ||
  abort("E2001: Failed to update vendor image.");
`
My device doesn't seem to have **_preload_** partition. Here are the named partitions of my device

/dev/block/mmcblk0p1	modem
/dev/block/mmcblk0p2	sec
/dev/block/mmcblk0p3	lksecapp
/dev/block/mmcblk0p4	lksecappbak
/dev/block/mmcblk0p5	cmnlib
/dev/block/mmcblk0p6	cmnlibbak
/dev/block/mmcblk0p7	cmnlib64
/dev/block/mmcblk0p8	cmnlib64bak
/dev/block/mmcblk0p9	keymaster
/dev/block/mmcblk0p10	keymasterbak
/dev/block/mmcblk0p11	aboot
/dev/block/mmcblk0p12	abootbak
/dev/block/mmcblk0p13	devinfo
/dev/block/mmcblk0p14	limits
/dev/block/mmcblk0p15	prov32
/dev/block/mmcblk0p16	prov32bak
/dev/block/mmcblk0p17	kpadA
/dev/block/mmcblk0p18	fsc
/dev/block/mmcblk0p19	ssd
/dev/block/mmcblk0p20	sbl1
/dev/block/mmcblk0p21	sbl1bak
/dev/block/mmcblk0p22	rpm
/dev/block/mmcblk0p23	rpmbak
/dev/block/mmcblk0p24	tz
/dev/block/mmcblk0p25	tzbak
/dev/block/mmcblk0p26	devcfg
/dev/block/mmcblk0p27	devcfgbak
/dev/block/mmcblk0p28	dsp
/dev/block/mmcblk0p29	modemst1
/dev/block/mmcblk0p30	modemst2
/dev/block/mmcblk0p31	DDR
/dev/block/mmcblk0p32	fsg
/dev/block/mmcblk0p33	kpadB
/dev/block/mmcblk0p34	boot
/dev/block/mmcblk0p35	recovery
/dev/block/mmcblk0p36	apdp
/dev/block/mmcblk0p37	msadp
/dev/block/mmcblk0p38	dpo
/dev/block/mmcblk0p39	splash
/dev/block/mmcblk0p40	misc
/dev/block/mmcblk0p41	keystore
/dev/block/mmcblk0p42	config
/dev/block/mmcblk0p43	oem
/dev/block/mmcblk0p44	mota
/dev/block/mmcblk0p45	dip
/dev/block/mmcblk0p46	mdtp
/dev/block/mmcblk0p47	syscfg
/dev/block/mmcblk0p48	mcfg
/dev/block/mmcblk0p49	persist
/dev/block/mmcblk0p50	cache
/dev/block/mmcblk0p51	mrd
/dev/block/mmcblk0p52	system
/dev/block/mmcblk0p53	vendor
/dev/block/mmcblk0p54	userdata

Could u pls suggest what to do regd this? Thanks a lot for your work on this device. I'm using latest twrp3.4.

**Comment by karthick111** [comment]
Flash this https://t.me/k6_development/96788 & then flash lineage-16.0, never roll back to discontinued ROMs.

**Comment by mtarunsai1999** [comment]
That url seems to be dead, could u pls check that

**Comment by karthick111** [comment]
Its your ISP, use vpn and join the group to view file

Don't start discussions here again like this, join that group to get possible helps for everything.
